### ISSUE TITLE
Dont know what is the best way to implement ftplugin-like functional

### ISSUE THREAD

**Issue by Liverm0r** [Olical/aniseed#110]
Best thing I came up to is to run an autoload.
[Example (commit)](https://github.com/Liverm0r/dotfiles/commit/2fd9b4c49968c4f05f1ca900813aef43f82c2d82) with loading clojure.fnl

Is it ok that way or is there a better approach?

**Comment by Olical** [comment]
Looks okay to me! If that works for you I'd stick with it. The only other approach I'd suggest requires looking in `:h api` at the functions you have available to you under the `vim.{method}` global Lua table.

If there's a function for registering autocmds you could use that instead of `ex` commands which is really just VimL. I find avoiding VimL interop wherever you can makes things easier.

You may be able to call an autocmd function from the API that takes a Lua function directly, which means you could wrap your Clojure setup code in a function and call it when the autocmd fires.

If that all works out and you find a function, you could even move your Clojure module require to an aniseed `autoload` in the `module` macro, then your autocmd just calls your setup method when you get into Clojure land and Aniseed will handle requiring it lazily for you.

What you have is already good, nothing wrong with it, this is just what I would look into. I hope this helps!

**Comment by Olical** [comment]
Closing since I think you have what you need 😄 please re-open if something goes wrong!

**Comment by D00mch** [comment]
I solved the problem by using symlinks. Comit example: https://github.com/D00mch/dotfiles/commit/1449d70e9d23debb2e7b61b087f0aca4c06090ab
