### ISSUE TITLE
Is it possible to refer :all like in clojure require?

### ISSUE THREAD

**Issue by Liverm0r** [Olical/aniseed#115]
Can't find it in docs or other issues.

Start thinking of making macroses that use `aniseed.core` under the hood to be able to call functions like `assoc` directyly, without prefix (`c.assoc`).

P.S.
Example, which doesn't work :) 
```fennel
 :assoc
 (fn [...]
   `(let [c# (require aniseed.core)]
     (c#.assoc ,...)))
```

**Comment by Olical** [comment]
Not yet, that doesn't exist, nor do I ever ever like using it or seeing it 😅 it's been pushed out of mainstream Clojure use for a reason, it's horribly hard to understand in most cases, some are okay (maybe core?... maybe at a push...) but people start to misuse it can cause all sorts of namespace soup.

If you REALLY want this, then a function or macro could be created that does it (I don't know how it'd work, it requires introducing many things into the global scope, that seems hard at compile time, if not impossible) which you'd put under `_G.require-all` for example.

Then in the module macro you could use `(module foo {require-all [my-module-name]})` which would call your function for you since the module macro passes through to some global function to handle the names.

**Comment by Liverm0r** [comment]
Ok, I will just use c.assoc without remorse :)

**Comment by Liverm0r** [comment]
yes, that's even better, I didn't know I could do this.

**Comment by Liverm0r** [comment]
It works, but I cant evaluate it in place.
```
unexpected multi symbol table: 0x010637f280

(module plugin.sandwich
^^^^^^^^^^^^^^^^^^^^^^^
* Try removing periods or colons from table: 0x010637f280.
```
```fennel
(module plugin.sandwich
  {require {nvim aniseed.nvim
            u util
            {: str : assoc} aniseed.core}})
```

**Comment by Olical** [comment]
Hm, yeah, I can reproduce, will look into it

**Comment by Olical** [comment]
Spent my lunch break on it but I think it's fixed now! Pretty tricky stuff to get right since now I have Fennel symbols in some places and tables in other places. So I have to guard against those types and behave differently at various layers.

**Comment by Olical** [comment]
I only added it this weekend and haven't had a chance to document it other
than tweeting it so far :D
