### ISSUE TITLE
Installing and Importing lua libraries

### ISSUE THREAD

**Issue by tami5** [Olical/aniseed#13]
Hay @Olical, sorry if this is extremely simple question. 

I'm trying to install a cool lib called lua fun, and I'd like to use it to develop my plugin, any suggestions?

Also, is it possible to use lib fun without prefix?

Thanks 🙏

**Comment by Olical** [comment]
You don't _need_ to use the prefixing / embedding script at all, I just use it as standard but it's not essential. It is really quite a bit hack so I get people not wanting to use it.

You can just put the Lua file in your `lua/` directory and then `require` it as you would any other module. You'll just need to write a script or something that fetches the lua file and puts it in your lua directory.

**Comment by tami5** [comment]
> You don't need to use the prefixing / embedding script at all, I just use it as standard but it's not essential. It is really quite a bit hack so I get people not wanting to use it.

Oh I believe you misunderstood what I meant. By without prefix, I meant using for example, `join` with out `str.join`. Speaking of `/` prefix, this is something I do miss from clojure, and it feels a bit wired using `.`. Wish if there's a way to use `/` for prefix to have a constant experience with clj dev.

> You can just put the Lua file in your lua/ directory and then require it as you would any other module. You'll just need to write a script or something that fetches the lua file and puts it in your lua directory.

Nice, very easy todo, thank you

**Comment by Olical** [comment]
Oh I'm sorry! So you meant import everything from `aniseed.string` into your current context. I don't think there's a way to do that in Lua at all, but I would _strongly_ recommend against it, also as a Clojure lover / user, `:refer-all` is always a nightmare for me when I'm maintaining old code myself or someone else wrote. Munging things together may be convenient for today but tomorrow's you will regret it, in my opinion.

And yeah, `/` to access modules could be really nice, I guess it'd require some really magic macro stuff or changes to the Fennel compiler? I don't _think_ there's a way to do it right now at all :thinking: would be neat though, I just got used to `.` in Fennel I guess because I think of the Lua semantics underneath.
