### ISSUE TITLE
reloading init.fnl on save

### ISSUE THREAD

**Issue by ColinRyan** [Olical/aniseed#17]
Hello,

I've been playing with fennel and aniseed for a little while and I'm trying to get it 
to reload my config when I make save changes to the init.fnl file. How would I go about
that these days? I was using :AniseedEvalFile before but that doesn't seem like a thing now .
Thanks :)

**Comment by Olical** [comment]
So if you're using Conjure you could map post file save to `<localleader>ef` (I recommend all Aniseed interactions go through Conjure since Aniseed is more of a toolkit now and Conjure is the UX that you use to interact with it).

However, if you don't want to use Conjure I'd recommend you do one of these things:

 * Write some Fennel/Lua that requires [aniseed.eval](https://github.com/Olical/aniseed/blob/e2eef631f580ff8582d70ea12f0cb02716b24825/fnl/aniseed/eval.fnl) and then run the entire buffer contents through it.
 * Alternatively, use [aniseed.compile's file function](https://github.com/Olical/aniseed/blob/e2eef631f580ff8582d70ea12f0cb02716b24825/fnl/aniseed/compile.fnl#L32-L43) to compile the `init.fnl` file into Lua somewhere then execute that with `:luafile ...` or similar.

Does this help at all? I know it's not a specific command for it but it's definitely only a couple of lines of code, I highly recommend hooking into internals of Conjure and Aniseed like this since I don't plan on changing them much now (and if I did it'd be a major version bump and well telegraphed).

On the other hand, if you REALLY want a command for this in Aniseed it could totally be added, `:AniseedEvalFile` could be risen from the dead and end up being quite useful, I just went down the route of making Aniseed a Fennel toolkit of Lua functions and Conjure hooks into. I'd lean towards just writing your own little things that hook into Aniseed personally.

**Comment by Olical** [comment]
I'm going to close this for now but happy to reopen if required. I think it's easy enough to map "on fennel file save" to a compile script or a call through to the `aniseed.compile` module in Lua space, I'd rather not add a bunch of commands since the primary interactive way to talking to Aniseed/Fennel is Conjure. All of the wiring that Conjure pokes to compile things is exposed in Aniseed as public functions that can be called anyway, like setting up a mapping to `some#viml#autoload#fn()` for example.

I hope this makes sense and you can work out a solution that suits your needs! If you have more questions or disagree with my stance on this please do let me know.
