### ISSUE TITLE
THIS IS INCREDIBLE

### ISSUE THREAD

**Issue by Kethku** [Olical/aniseed#4]
I just wanted to say this project is amazing. Fantastic work. Carry on

**Comment by Olical** [comment]
Thank you so very much for your kind words, I'm so glad you like the look of it so far!

I hope it'll be a little more accessible when I finish the full development environment and API documentation!

**Comment by Kethku** [comment]
Something like this would be an amazing base for a spacemacs like distribution. Just saying

**Comment by Olical** [comment]
Very true! I'd rather someone built that on top of Aniseed personally, that's not something I have time for or interest to do right now. I've got all my time going into Conjure since I love making interactive eval tooling (which will be the way to work on Aniseed projects soon too!).

As much as I love and appreciate this issue, I'm going to close it just because it should be closed eventually :sweat_smile: thank you so much again! It's massively appreciated, I hope to get full vim help docs for the entire API in soon!

**Comment by Kethku** [comment]
@Olical Side note: I've enjoyed this kind of thing in my projects using the discussion feature. Github has the ability to convert an issue to a discussion once you have enabled the feature, so I keep messages like this one around there. Plus it introduces a very nice separation between Q&A type issues and actual bugs/feature requests. I highly recommend it.

**Comment by Olical** [comment]
Ohh okay, maybe I'll give that a go now, I've never used it before!
