### ISSUE TITLE
`aniseed.core.assoc` assigning multiple keys & values

### ISSUE THREAD

**Issue by smolck** [Olical/aniseed#7]
Currently, `aniseed.core.assoc` only allows for a single key-value pair:
```clojure
(assoc {} :stuff 5} ; => {:stuff 5}

(assoc {} :stuff 5 :things 4) ; Doesn't work, only gives `{:stuff 5}`
```
Would it be possible to make that second example possible, like with [Clojure's `assoc`](https://clojuredocs.org/clojure.core/assoc)? Maybe using a [variadic function](https://fennel-lang.org/tutorial#variadic-functions)?

If making a variadic version of `assoc` wouldn't work, then maybe something like this would work?
```clojure
(assoc {} {:stuff 5 :things 4}) ; => {:stuff 5 :things 4}
```
For that version, this should be basically all that's needed, right?
```clojure
(defn assoc [tbl kv-tbl]
  (let [tbl (or tbl {})]
    (each [k v (pairs kv-tbl)]
      (tset tbl k v)
    tbl))
```

As an aside, thank you immensely for making this library. Combined with Conjure, working with Fennel and Neovim is a _wonderful_ experience! Keep up the amazing work!

**Comment by Olical** [comment]
Hmm, it's definitely possible, it's actually a feature of assoc that I never really use so I sort of forgot about it. As soon as I have more than one thing I use merge since I can layer things up and use `when` to conditionally merge some parts.

```
(a.merge
  {:foo 1}
  (when tuesday?
    {:bar 2})
  {:baz 3
   :etc 4})
```

I'll have a little think about implementing it and how it could affect performance for the normal one key case. Perhaps two paths, one for varargs and one for a single key would be best :thinking:

I actually need to write a `time` function or macro so I can begin writing some benchmarking tools :sweat_smile:

**Comment by Olical** [comment]
And thank you very much for the kind words! It's very appreciated :blush:

**Comment by Olical** [comment]
Added to develop in a way that should work efficiently and correctly.
