### ISSUE TITLE
Aniseed macros sans Neovim?

### ISSUE THREAD

**Issue by atweiden** [Olical/aniseed#8]
`def`, `defn` et al [beautify Fennel](https://github.com/atweiden/vim-fennel#screenshot), and make things flow more naturally. Between Neovim's first-class Lua support, Conjure and Fennel, we have the makings of an unbelievably well-integrated developer experience for Vim

However, there's a big issue as of today standing in the way of writing small Fennel libraries with a [conversational approach to development](https://oli.me.uk/conversational-software-development/). For example, imagine running `fennel script.fnl` where `script.fnl` defines its functions with `defn`. Or perhaps `fennel -l aniseed-macros.fnl script.fnl`. Sadly, it isn't possible to do this currently, even when you prefix `script.fnl` with `(require-macros :path/to/aniseed/macros.fnl)`.

Instead it seems necessary to fundamentally rearchitect `script.fnl` as an extension of Olical/aniseed, per how Conjure does it, in order to write code with `defn`. That's a heavy burden to place on an otherwise lightweight Fennel script or library. Frustratingly so, because without writing Fennel with Aniseed's macros, it becomes difficult to interactively develop Fennel with Conjure: Conjure assumes you use `defn` et al in your Fennel, but it's just the opposite with the normal Fennel compiler, which doesn't seem to understand Aniseed's macros in the absence of Aniseed's compiler toolchain.

Speaking for myself, I'd love to have the ability to write all my Fennel code with `defn` etc, and then also optionally eval my code in Neovim with Conjure. But there's got to be a way to do that without fundamentally rearchitecting small libs; perhaps it could be accomplished through a luarocks lib.

I'd be more than willing to turn Aniseed's macros into an independent library for this purpose, but I haven't been able to figure out how to do so. I'm starting to suspect a clean implementation of this would require modifying the Fennel compiler. I'd greatly appreciate reading your thoughts on this.

**Comment by Olical** [comment]
Hey! This is a really good point and I kinda thought about this but had no real need so I didn't push further for it... yet. I do need to add external Fennel REPL development for when you're working on non-Neovim Fennel projects (such as a Fennel REPL embedded within a Lua game project or something).

I can't see a reason why the macros can't be used in CLI Fennel compilation, after all, that's what I do in the makefile! I'll have a play and see if I can get a simple Aniseed sans Neovim project working, although you probably won't be able to use the majority of the standard library since some of it leans on Neovim itself, we'll have to just experiment with that.

I _suspect_ the problem is that your Fennel file is requiring more Fennel which normally is okay, Fennel would just compile it on the fly through the loaded. That's the point that the macros need to be inserted again, where A requires B, you have the macros for A but the require of B does not.

I get around this by compiling each .fnl -> .lua in isolation with the macros, then I never really _run_ fennel, I compile it AOT then execute the Lua. This difference means Fennel's module loading system never kicks in to try and compile more Fennel without the macros. If that makes sense?

So two possible steps:

 1. AOT compile with the macros then work with Lua (probably not ideal)
 2. Configure Fennel and it's loaded to inject the macros to all subsequent required Fennel files that aren't Lua yet before they're compiled.

What do you think? Thanks for bringing this up, it'd be great to get this working in more places. Also thanks for the support in your syntax highlighting fork! It looks really good! I'll have to swap over!

**Comment by atweiden** [comment]
> I can't see a reason why the macros can't be used in CLI Fennel compilation, after all, that's what I do in the makefile.

Indeed, I was able to replicate the makefile's actions, but ... this got me AOT compiled Lua files. I didn't quite know what to make of this. It was a little mind bending to ponder how dependencies declared in the Fennel files would get resolved.

> I get around this by compiling each .fnl -> .lua in isolation with the macros, then I never really run fennel, I compile it AOT then execute the Lua. This difference means Fennel's module loading system never kicks in to try and compile more Fennel without the macros. If that makes sense?

From this it sounds like Aniseed is transpiling each Fennel file to Lua and then expecting Lua to do the `require`ing. This seems like an OK developer experience, if a bit unnatural. Granted, since I'm so excited by the potential of Neovim/Conjure/Fennel, I think I could live with that. I'm just not sure how I feel about sticking `fnl` and `lua` directories in all my Fennel repos to facilitate this approach. Ultimately I really just want Conjure to work well. But I also want the freedom to develop small libraries in Fennel which make use of Aniseed's macros without having to involve a large hammer as such. Frankly, `defn` et al strike me as belonging in Fennel core.

Shrugs. Admittedly I'm entirely unfamiliar with how Typescript, or Reason, or various modern transpilers do things. Maybe parallels could be drawn with Aniseed/Fennel/Lua there.

> Also thanks for the support in your syntax highlighting fork! It looks really good! I'll have to swap over!

Thanks very much. I feel like Neovim/Fennel/Conjure could be the developer environment trifecta, and I put considerable effort into making Fennel syntax highlighting sing -- for [junegunn/seoul256.vim](https://github.com/junegunn/seoul256.vim). As for whether it'll integrate well with your current Vim color scheme, that's a different question. I could somewhat rectify this by linking vim-fennel's keyword groups to Fennel-specific "middleman" highlight groups. This would allow color schemes to override the middleman highlighting groups for Fennel, e.g. you could write `highlight fennelFunction ctermfg=161 guifg=#DF005F` (or whatever looks best in your particular color scheme).

**Comment by Olical** [comment]
Aniseed as it stands isn't relying on Fennel's file resolving, that's not a fully conscious choice but I do like how it's extremely close to Lua, which is good since I'm relying on so many existing Lua things. Maybe I'll rethink and design that!

The only reason I'm AOTing like this and committing the code is so that the end user just gets Lua that can execute directly with no performance (if it's a big project), system or environment inconsistencies causing the compile to fail or output something different. I'm not married to that idea, I actually considered having a sort of auto compile of fnl->lua as the plugin loads but decided against it because it was more things that could go wrong.

If you delete a fnl file you end up with a hanging lua file in _some users_ plugin clones, how do you clean those? Do you always rm everything before you compile? But then you compile the whole plugin every time? I could go on, but my point is, as soon as you make it smart and _only_ fnl (with auto lua compile) you run into a lot more questions and complexities. They're not impossible to solve, but they are harder than just "compile aot and use lua for the end user".

I think using the macros outside of Neovim in a normal Fennel project would be a great change, regardless. I'm totally open to only committing fennel and auto compiling when nvim opens, it just means bundling fennel.lua with your plugin to _do_ the compiling, so... tradeoffs!

Having the option could be great, I don't mind duplicating the fnl->lua code, it's really not that many bytes in the grand scheme of things. I like having something simple and robust that uses a few more bytes than it has to. The end user should hopefully never notice the difference if they don't peek under the hood, I do totally understand the kinda grossness of committing the lua though, it's something I thought about for a good few weeks. Having the option for either approach could be great.

**Comment by atweiden** [comment]
Right -- AOT compiling to Lua makes more sense to me now, particularly in a Neovim plugin context. I'll see what I can throw together with that approach independent of a Neovim plugin context. In the back of my mind though, I'm a bit worried about how debugging Fennel may be impacted by having the entire Fennel codebase only executable post-transpilation. Is that a valid concern?

Alternatively, say I forked Fennel and added `defn` et al as specials in the compiler core (or maybe added them as macros). I could see myself preferring that over maintaining Makefiles and fnl/lua dirs. Do you have any input along those lines? E.g. how would you approach implementing the `:aniseed/locals` tables for `def-` and so forth in the core compiler? All said, on balance I'm equally as interested in exploring this route. I can always maintain a Fennel fork I think. Maybe I'll try both ways.

**Comment by Olical** [comment]
So normally when I execute Fennel from within Aniseed I actually run it _through_ Fennel so that stack traces align. Once it's into Lua land (pre-compiled and being used by end users) your stack trace will be for the Lua. Luckily Fennel aligns near enough 1-1 with the outputted Lua, I think I even set the compiler flag to align it as much as possible but I can't recall.

I haven't had an issue with it while doing this in "production" for months (a year?).

I think adding def etc to Fennel will only ever be in a fork, I can't say I'd recommend it? I'd rather lean on mainline Fennel and work within it's confines. If a new arg to Fennel like "always load this macro before compiling a file" were added though... some sort of hook could work well. Could be worth having a dig through docs / source (it's semi-approachable) or even raising an issue about "how can I have a macro file loaded for _every_ module that's being compiled?".

**Comment by atweiden** [comment]
Consider my interest piqued.
